"use strict";

require("dotenv").config();

const conf = process.env;

const SESSION_SECRET = conf.SESSION_SECRET;
const MONGO_URI = conf.MONGO_URI;
const PORT = conf.PORT;
const EMAIL_USER = conf.EMAIL_USER;
const EMAIL_PASSWORD = conf.EMAIL_PASSWORD;

const GITHUB_CLIENT_ID = conf.L_GH_ID || conf.GH_CLIENT_ID;
const GITHUB_CLIENT_SECRET = conf.L_GH_SECRET || conf.GH_CLIENT_SECRET;
const GITHUB_CALLBACK_URL = conf.GH_CALLBACK_URL;

const FACEBOOK_APP_ID = conf.FB_APP_ID;
const FACEBOOK_APP_SECRET = conf.FB_APP_SECRET;

const PRODUCTION = conf.PRODUCTION;

module.exports = {
  SESSION_SECRET,
  MONGO_URI,
  PORT,
  EMAIL_USER,
  EMAIL_PASSWORD,
  GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET,
  GITHUB_CALLBACK_URL,
  FACEBOOK_APP_ID,
  FACEBOOK_APP_SECRET,
  PRODUCTION,
};
